# Generated by Django 2.2 on 2020-11-19 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0002_auto_20201015_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
