# Generated by Django 2.2 on 2020-11-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20201119_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='used',
            new_name='number',
        ),
    ]
