# Generated by Django 2.2 on 2020-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201108_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'new'), ('S', 'sale')], max_length=1, null=True),
        ),
    ]
