# Generated by Django 2.2 on 2020-11-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_instagrammedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramMedia',
        ),
    ]
