# Generated by Django 2.2 on 2020-10-09 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('novaposhta', '0003_auto_20201009_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=250, verbose_name='Message')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novaposhta.Area', verbose_name='Area')),
                ('nova_city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='area', chained_model_field='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novaposhta.City', verbose_name='Nova Poshta City')),
                ('nova_warehouse', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='nova_city', chained_model_field='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='novaposhta.Warehouse', verbose_name='Nova Poshta Warehouse')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
    ]
